FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Expose the port that the Flask app will run on
EXPOSE 5000

# Run the Flask app
CMD ["python", "api/app.py"]
